<?php

namespace App\Dto\Tmdb;

use App\Dto\Tmdb\Clients\SearchApi\SearchApiInterface;
use App\Dto\Tmdb\Clients\DiscoverApi\DiscoverApiInterface;
use App\Dto\Tmdb\Clients\MovieApi\MovieApiInterface;
use App\Dto\Tmdb\Clients\TvApi\TvApiInterface;
use App\Dto\Tmdb\Clients\ConfigurationApi\ConfigurationApiInterface;
use App\Dto\Tmdb\Clients\TrendingApi\TrendingApiInterface;
use App\Dto\Tmdb\Clients\AuthenticationApi\AuthenticationApiInterface;
use App\Dto\Tmdb\Clients\FindApi\FindApiInterface;
use App\Dto\Tmdb\Clients\PersonApi\PersonApiInterface;
use App\Dto\Tmdb\Clients\AccountApi\AccountApiInterface;
use App\Dto\Tmdb\Clients\CertificationApi\CertificationApiInterface;
use App\Dto\Tmdb\Clients\CollectionApi\CollectionApiInterface;
use App\Dto\Tmdb\Clients\CompanyApi\CompanyApiInterface;
use App\Dto\Tmdb\Clients\CreditApi\CreditApiInterface;
use App\Dto\Tmdb\Clients\GenreApi\GenreApiInterface;
use App\Dto\Tmdb\Clients\GuestSessionApi\GuestSessionApiInterface;
use App\Dto\Tmdb\Clients\WatchApi\WatchApiInterface;
use App\Dto\Tmdb\Clients\KeywordApi\KeywordApiInterface;
use App\Dto\Tmdb\Clients\ListApi\ListApiInterface;
use App\Dto\Tmdb\Clients\NetworkApi\NetworkApiInterface;
use App\Dto\Tmdb\Clients\ReviewApi\ReviewApiInterface;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface TmdbClientInterface
{
    public function searchApi(): SearchApiInterface;

    public function discoverApi(): DiscoverApiInterface;

    public function movieApi(): MovieApiInterface;

    public function tvApi(): TvApiInterface;

    public function configurationApi(): ConfigurationApiInterface;

    public function trendingApi(): TrendingApiInterface;

    public function authenticationApi(): AuthenticationApiInterface;

    public function findApi(): FindApiInterface;

    public function personApi(): PersonApiInterface;

    public function accountApi(): AccountApiInterface;

    public function certificationApi(): CertificationApiInterface;

    public function collectionApi(): CollectionApiInterface;

    public function companyApi(): CompanyApiInterface;

    public function creditApi(): CreditApiInterface;

    public function genreApi(): GenreApiInterface;

    public function guestSessionApi(): GuestSessionApiInterface;

    public function watchApi(): WatchApiInterface;

    public function keywordApi(): KeywordApiInterface;

    public function listApi(): ListApiInterface;

    public function networkApi(): NetworkApiInterface;

    public function reviewApi(): ReviewApiInterface;
}