<?php

namespace App\Dto\Tmdb\Responses\Watch;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class WatchProviderTvListResultsDisplayPriorities
{
    #[SerializedName('CA')]
    private ?int $CA = null;
    #[SerializedName('AE')]
    private ?int $AE = null;
    #[SerializedName('AR')]
    private ?int $AR = null;
    #[SerializedName('AT')]
    private ?int $AT = null;
    #[SerializedName('AU')]
    private ?int $AU = null;
    #[SerializedName('BE')]
    private ?int $BE = null;
    #[SerializedName('BO')]
    private ?int $BO = null;
    #[SerializedName('BR')]
    private ?int $BR = null;
    #[SerializedName('BG')]
    private ?int $BG = null;
    #[SerializedName('CH')]
    private ?int $CH = null;
    #[SerializedName('CL')]
    private ?int $CL = null;
    #[SerializedName('CO')]
    private ?int $CO = null;
    #[SerializedName('CR')]
    private ?int $CR = null;
    #[SerializedName('CZ')]
    private ?int $CZ = null;
    #[SerializedName('DE')]
    private ?int $DE = null;
    #[SerializedName('DK')]
    private ?int $DK = null;
    #[SerializedName('EC')]
    private ?int $EC = null;
    #[SerializedName('EE')]
    private ?int $EE = null;
    #[SerializedName('EG')]
    private ?int $EG = null;
    #[SerializedName('ES')]
    private ?int $ES = null;
    #[SerializedName('FI')]
    private ?int $FI = null;
    #[SerializedName('FR')]
    private ?int $FR = null;
    #[SerializedName('GB')]
    private ?int $GB = null;
    #[SerializedName('GR')]
    private ?int $GR = null;
    #[SerializedName('GT')]
    private ?int $GT = null;
    #[SerializedName('HK')]
    private ?int $HK = null;
    #[SerializedName('HN')]
    private ?int $HN = null;
    #[SerializedName('HU')]
    private ?int $HU = null;
    #[SerializedName('ID')]
    private ?int $ID = null;
    #[SerializedName('IE')]
    private ?int $IE = null;
    #[SerializedName('IN')]
    private ?int $IN = null;
    #[SerializedName('IT')]
    private ?int $IT = null;
    #[SerializedName('JP')]
    private ?int $JP = null;
    #[SerializedName('LT')]
    private ?int $LT = null;
    #[SerializedName('LV')]
    private ?int $LV = null;
    #[SerializedName('MX')]
    private ?int $MX = null;
    #[SerializedName('MY')]
    private ?int $MY = null;
    #[SerializedName('NL')]
    private ?int $NL = null;
    #[SerializedName('NO')]
    private ?int $NO = null;
    #[SerializedName('NZ')]
    private ?int $NZ = null;
    #[SerializedName('PE')]
    private ?int $PE = null;
    #[SerializedName('PH')]
    private ?int $PH = null;
    #[SerializedName('PL')]
    private ?int $PL = null;
    #[SerializedName('PT')]
    private ?int $PT = null;
    #[SerializedName('PY')]
    private ?int $PY = null;
    #[SerializedName('RU')]
    private ?int $RU = null;
    #[SerializedName('SA')]
    private ?int $SA = null;
    #[SerializedName('SE')]
    private ?int $SE = null;
    #[SerializedName('SG')]
    private ?int $SG = null;
    #[SerializedName('SK')]
    private ?int $SK = null;
    #[SerializedName('TH')]
    private ?int $TH = null;
    #[SerializedName('TR')]
    private ?int $TR = null;
    #[SerializedName('TW')]
    private ?int $TW = null;
    #[SerializedName('US')]
    private ?int $US = null;
    #[SerializedName('VE')]
    private ?int $VE = null;
    #[SerializedName('ZA')]
    private ?int $ZA = null;
    #[SerializedName('SI')]
    private ?int $SI = null;
    #[SerializedName('CV')]
    private ?int $CV = null;
    #[SerializedName('GH')]
    private ?int $GH = null;
    #[SerializedName('MU')]
    private ?int $MU = null;
    #[SerializedName('MZ')]
    private ?int $MZ = null;
    #[SerializedName('UG')]
    private ?int $UG = null;
    #[SerializedName('IL')]
    private ?int $IL = null;

    public function getCA(): ?int
    {
        return $this->CA;
    }

    public function setCA(?int $CA): self
    {
        $this->CA = $CA;

        return $this;
    }

    public function getAE(): ?int
    {
        return $this->AE;
    }

    public function setAE(?int $AE): self
    {
        $this->AE = $AE;

        return $this;
    }

    public function getAR(): ?int
    {
        return $this->AR;
    }

    public function setAR(?int $AR): self
    {
        $this->AR = $AR;

        return $this;
    }

    public function getAT(): ?int
    {
        return $this->AT;
    }

    public function setAT(?int $AT): self
    {
        $this->AT = $AT;

        return $this;
    }

    public function getAU(): ?int
    {
        return $this->AU;
    }

    public function setAU(?int $AU): self
    {
        $this->AU = $AU;

        return $this;
    }

    public function getBE(): ?int
    {
        return $this->BE;
    }

    public function setBE(?int $BE): self
    {
        $this->BE = $BE;

        return $this;
    }

    public function getBO(): ?int
    {
        return $this->BO;
    }

    public function setBO(?int $BO): self
    {
        $this->BO = $BO;

        return $this;
    }

    public function getBR(): ?int
    {
        return $this->BR;
    }

    public function setBR(?int $BR): self
    {
        $this->BR = $BR;

        return $this;
    }

    public function getBG(): ?int
    {
        return $this->BG;
    }

    public function setBG(?int $BG): self
    {
        $this->BG = $BG;

        return $this;
    }

    public function getCH(): ?int
    {
        return $this->CH;
    }

    public function setCH(?int $CH): self
    {
        $this->CH = $CH;

        return $this;
    }

    public function getCL(): ?int
    {
        return $this->CL;
    }

    public function setCL(?int $CL): self
    {
        $this->CL = $CL;

        return $this;
    }

    public function getCO(): ?int
    {
        return $this->CO;
    }

    public function setCO(?int $CO): self
    {
        $this->CO = $CO;

        return $this;
    }

    public function getCR(): ?int
    {
        return $this->CR;
    }

    public function setCR(?int $CR): self
    {
        $this->CR = $CR;

        return $this;
    }

    public function getCZ(): ?int
    {
        return $this->CZ;
    }

    public function setCZ(?int $CZ): self
    {
        $this->CZ = $CZ;

        return $this;
    }

    public function getDE(): ?int
    {
        return $this->DE;
    }

    public function setDE(?int $DE): self
    {
        $this->DE = $DE;

        return $this;
    }

    public function getDK(): ?int
    {
        return $this->DK;
    }

    public function setDK(?int $DK): self
    {
        $this->DK = $DK;

        return $this;
    }

    public function getEC(): ?int
    {
        return $this->EC;
    }

    public function setEC(?int $EC): self
    {
        $this->EC = $EC;

        return $this;
    }

    public function getEE(): ?int
    {
        return $this->EE;
    }

    public function setEE(?int $EE): self
    {
        $this->EE = $EE;

        return $this;
    }

    public function getEG(): ?int
    {
        return $this->EG;
    }

    public function setEG(?int $EG): self
    {
        $this->EG = $EG;

        return $this;
    }

    public function getES(): ?int
    {
        return $this->ES;
    }

    public function setES(?int $ES): self
    {
        $this->ES = $ES;

        return $this;
    }

    public function getFI(): ?int
    {
        return $this->FI;
    }

    public function setFI(?int $FI): self
    {
        $this->FI = $FI;

        return $this;
    }

    public function getFR(): ?int
    {
        return $this->FR;
    }

    public function setFR(?int $FR): self
    {
        $this->FR = $FR;

        return $this;
    }

    public function getGB(): ?int
    {
        return $this->GB;
    }

    public function setGB(?int $GB): self
    {
        $this->GB = $GB;

        return $this;
    }

    public function getGR(): ?int
    {
        return $this->GR;
    }

    public function setGR(?int $GR): self
    {
        $this->GR = $GR;

        return $this;
    }

    public function getGT(): ?int
    {
        return $this->GT;
    }

    public function setGT(?int $GT): self
    {
        $this->GT = $GT;

        return $this;
    }

    public function getHK(): ?int
    {
        return $this->HK;
    }

    public function setHK(?int $HK): self
    {
        $this->HK = $HK;

        return $this;
    }

    public function getHN(): ?int
    {
        return $this->HN;
    }

    public function setHN(?int $HN): self
    {
        $this->HN = $HN;

        return $this;
    }

    public function getHU(): ?int
    {
        return $this->HU;
    }

    public function setHU(?int $HU): self
    {
        $this->HU = $HU;

        return $this;
    }

    public function getID(): ?int
    {
        return $this->ID;
    }

    public function setID(?int $ID): self
    {
        $this->ID = $ID;

        return $this;
    }

    public function getIE(): ?int
    {
        return $this->IE;
    }

    public function setIE(?int $IE): self
    {
        $this->IE = $IE;

        return $this;
    }

    public function getIN(): ?int
    {
        return $this->IN;
    }

    public function setIN(?int $IN): self
    {
        $this->IN = $IN;

        return $this;
    }

    public function getIT(): ?int
    {
        return $this->IT;
    }

    public function setIT(?int $IT): self
    {
        $this->IT = $IT;

        return $this;
    }

    public function getJP(): ?int
    {
        return $this->JP;
    }

    public function setJP(?int $JP): self
    {
        $this->JP = $JP;

        return $this;
    }

    public function getLT(): ?int
    {
        return $this->LT;
    }

    public function setLT(?int $LT): self
    {
        $this->LT = $LT;

        return $this;
    }

    public function getLV(): ?int
    {
        return $this->LV;
    }

    public function setLV(?int $LV): self
    {
        $this->LV = $LV;

        return $this;
    }

    public function getMX(): ?int
    {
        return $this->MX;
    }

    public function setMX(?int $MX): self
    {
        $this->MX = $MX;

        return $this;
    }

    public function getMY(): ?int
    {
        return $this->MY;
    }

    public function setMY(?int $MY): self
    {
        $this->MY = $MY;

        return $this;
    }

    public function getNL(): ?int
    {
        return $this->NL;
    }

    public function setNL(?int $NL): self
    {
        $this->NL = $NL;

        return $this;
    }

    public function getNO(): ?int
    {
        return $this->NO;
    }

    public function setNO(?int $NO): self
    {
        $this->NO = $NO;

        return $this;
    }

    public function getNZ(): ?int
    {
        return $this->NZ;
    }

    public function setNZ(?int $NZ): self
    {
        $this->NZ = $NZ;

        return $this;
    }

    public function getPE(): ?int
    {
        return $this->PE;
    }

    public function setPE(?int $PE): self
    {
        $this->PE = $PE;

        return $this;
    }

    public function getPH(): ?int
    {
        return $this->PH;
    }

    public function setPH(?int $PH): self
    {
        $this->PH = $PH;

        return $this;
    }

    public function getPL(): ?int
    {
        return $this->PL;
    }

    public function setPL(?int $PL): self
    {
        $this->PL = $PL;

        return $this;
    }

    public function getPT(): ?int
    {
        return $this->PT;
    }

    public function setPT(?int $PT): self
    {
        $this->PT = $PT;

        return $this;
    }

    public function getPY(): ?int
    {
        return $this->PY;
    }

    public function setPY(?int $PY): self
    {
        $this->PY = $PY;

        return $this;
    }

    public function getRU(): ?int
    {
        return $this->RU;
    }

    public function setRU(?int $RU): self
    {
        $this->RU = $RU;

        return $this;
    }

    public function getSA(): ?int
    {
        return $this->SA;
    }

    public function setSA(?int $SA): self
    {
        $this->SA = $SA;

        return $this;
    }

    public function getSE(): ?int
    {
        return $this->SE;
    }

    public function setSE(?int $SE): self
    {
        $this->SE = $SE;

        return $this;
    }

    public function getSG(): ?int
    {
        return $this->SG;
    }

    public function setSG(?int $SG): self
    {
        $this->SG = $SG;

        return $this;
    }

    public function getSK(): ?int
    {
        return $this->SK;
    }

    public function setSK(?int $SK): self
    {
        $this->SK = $SK;

        return $this;
    }

    public function getTH(): ?int
    {
        return $this->TH;
    }

    public function setTH(?int $TH): self
    {
        $this->TH = $TH;

        return $this;
    }

    public function getTR(): ?int
    {
        return $this->TR;
    }

    public function setTR(?int $TR): self
    {
        $this->TR = $TR;

        return $this;
    }

    public function getTW(): ?int
    {
        return $this->TW;
    }

    public function setTW(?int $TW): self
    {
        $this->TW = $TW;

        return $this;
    }

    public function getUS(): ?int
    {
        return $this->US;
    }

    public function setUS(?int $US): self
    {
        $this->US = $US;

        return $this;
    }

    public function getVE(): ?int
    {
        return $this->VE;
    }

    public function setVE(?int $VE): self
    {
        $this->VE = $VE;

        return $this;
    }

    public function getZA(): ?int
    {
        return $this->ZA;
    }

    public function setZA(?int $ZA): self
    {
        $this->ZA = $ZA;

        return $this;
    }

    public function getSI(): ?int
    {
        return $this->SI;
    }

    public function setSI(?int $SI): self
    {
        $this->SI = $SI;

        return $this;
    }

    public function getCV(): ?int
    {
        return $this->CV;
    }

    public function setCV(?int $CV): self
    {
        $this->CV = $CV;

        return $this;
    }

    public function getGH(): ?int
    {
        return $this->GH;
    }

    public function setGH(?int $GH): self
    {
        $this->GH = $GH;

        return $this;
    }

    public function getMU(): ?int
    {
        return $this->MU;
    }

    public function setMU(?int $MU): self
    {
        $this->MU = $MU;

        return $this;
    }

    public function getMZ(): ?int
    {
        return $this->MZ;
    }

    public function setMZ(?int $MZ): self
    {
        $this->MZ = $MZ;

        return $this;
    }

    public function getUG(): ?int
    {
        return $this->UG;
    }

    public function setUG(?int $UG): self
    {
        $this->UG = $UG;

        return $this;
    }

    public function getIL(): ?int
    {
        return $this->IL;
    }

    public function setIL(?int $IL): self
    {
        $this->IL = $IL;

        return $this;
    }
}