<?php

namespace App\Dto\Tmdb\Responses\Genre;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class GenreTvList
{
    /**
     * @var array<GenreTvListGenres>
     */
    #[SerializedName('genres')]
    private array $genres = [];

    /**
     * @return array<GenreTvListGenres>
     */
    public function getGenres(): array
    {
        return $this->genres;
    }

    /**
     * @param array<GenreTvListGenres> $genres
     */
    public function setGenres(array $genres): self
    {
        $this->genres = $genres;

        return $this;
    }
}