framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        
        envelope:
            sender: '%env(MAILER_SENDER_ADDRESS)%'

        headers:
            from: 'MovieDB Mailbot <%env(MAILER_SENDER_ADDRESS)%>'
