tmdb_symfony:
    api_key: bd705be33361e89eae53e325178ae8ef
    cache:
        enabled: true
        adapter: cache.tmdb
    options:
        bearer_token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiZDcwNWJlMzMzNjFlODllYWU1M2UzMjUxNzhhZThlZiIsInN1YiI6IjY1ZTBiYWU4NTFmOTlhMDE2MjU2NzAyNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.pQ1ZLroLE17Ay_74cLPowa-b3cMvhaTNUpfmRRLHDiw
        http:
            client: Symfony\Component\HttpClient\Psr18Client
            request_factory: Nyholm\Psr7\Factory\Psr17Factory
            response_factory: Nyholm\Psr7\Factory\Psr17Factory
            stream_factory: Nyholm\Psr7\Factory\Psr17Factory
            uri_factory: Nyholm\Psr7\Factory\Psr17Factory
        secure: true
        host: api.themoviedb.org/3
        guest_session_token: null
        event_dispatcher:
            adapter: event_dispatcher
        hydration:
            event_listener_handles_hydration: false
            only_for_specified_models: { }
        api_token: bd705be33361e89eae53e325178ae8ef # you don't have to set this if you set it at the root level