workers:
  npm_encore_watch:
    cmd: [ 'npx', 'encore', 'dev', '--watch' ]

  docker_compose:
    cmd: [ 'docker-compose', 'up']

  typescript:
    cmd: [ 'symfony', 'console', 'typescript:build', '--watch' ]

  # Only works when *not* starting the local web server as a daemon
  messenger_consume_async:
    cmd: ['symfony', 'console', 'messenger:consume', 'async']
    watch: ['config', 'src', 'templates', 'vendor']