# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MAILER_DSN: ${MAILER_DSN}
      # Set FRANKENPHP_CONFIG to an empty string because of
      # this issue https://github.com/EasyCorp/EasyAdminBundle/issues/5986
      # Should be fixed with https://github.com/EasyCorp/EasyAdminBundle/pull/6273
      # But it's not merged yet
      FRANKENPHP_CONFIG: ''
      
  php-worker:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MAILER_DSN: ${MAILER_DSN}
      FRANKENPHP_CONFIG: ''

  redis:
    volumes:
      - ./docker/redis.prod.conf:/usr/local/etc/redis/redis.conf
