<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvEpisodeAccountStates
{
    #[SerializedName('id')]
    private ?int $id = null;
    #[SerializedName('favorite')]
    private ?bool $favorite = null;
    #[SerializedName('rated')]
    private ?TvEpisodeAccountStatesRated $rated = null;
    #[SerializedName('watchlist')]
    private ?bool $watchlist = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getFavorite(): ?bool
    {
        return $this->favorite;
    }

    public function setFavorite(?bool $favorite): self
    {
        $this->favorite = $favorite;

        return $this;
    }

    public function getRated(): ?TvEpisodeAccountStatesRated
    {
        return $this->rated;
    }

    public function setRated(?TvEpisodeAccountStatesRated $rated): self
    {
        $this->rated = $rated;

        return $this;
    }

    public function getWatchlist(): ?bool
    {
        return $this->watchlist;
    }

    public function setWatchlist(?bool $watchlist): self
    {
        $this->watchlist = $watchlist;

        return $this;
    }
}