<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;
use Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvEpisodeCredits
{
    /**
     * @var array<TvEpisodeCreditsCast>
     */
    #[SerializedName('cast')]
    private array $cast = [];
    /**
     * @var array<TvEpisodeCreditsCrew>
     */
    #[SerializedName('crew')]
    private array $crew = [];
    /**
     * @var array<TvEpisodeCreditsGuestStars>
     */
    #[SerializedName('guest_stars')]
    private array $guestStars = [];
    #[SerializedName('id')]
    private ?int $id = null;

    public static function fromArray(array $data = []): self
    {
        $serializer = new Serializer([new ObjectNormalizer(nameConverter: new CamelCaseToSnakeCaseNameConverter()), new ArrayDenormalizer()]);
        return $serializer->denormalize($data, self::class);
    }

    public function toArray(): array
    {
        $serializer = new Serializer([new ObjectNormalizer(nameConverter: new CamelCaseToSnakeCaseNameConverter()), new ArrayDenormalizer()]);
        return $serializer->normalize($this);
    }

    /**
     * @return array<TvEpisodeCreditsCast>
     */
    public function getCast(): array
    {
        return $this->cast;
    }

    /**
     * @param array<TvEpisodeCreditsCast> $cast
     */
    public function setCast(array $cast): self
    {
        $this->cast = $cast;

        return $this;
    }

    /**
     * @return array<TvEpisodeCreditsCrew>
     */
    public function getCrew(): array
    {
        return $this->crew;
    }

    /**
     * @param array<TvEpisodeCreditsCrew> $crew
     */
    public function setCrew(array $crew): self
    {
        $this->crew = $crew;

        return $this;
    }

    /**
     * @return array<TvEpisodeCreditsGuestStars>
     */
    public function getGuestStars(): array
    {
        return $this->guestStars;
    }

    /**
     * @param array<TvEpisodeCreditsGuestStars> $guestStars
     */
    public function setGuestStars(array $guestStars): self
    {
        $this->guestStars = $guestStars;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }
}