<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeriesChangesChangesItems
{
    #[SerializedName('id')]
    private ?string $id = null;
    #[SerializedName('action')]
    private ?string $action = null;
    #[SerializedName('time')]
    private ?string $time = null;
    #[SerializedName('iso_639_1')]
    private ?string $iso6391 = null;
    #[SerializedName('iso_3166_1')]
    private ?string $iso31661 = null;
    #[SerializedName('value')]
    private ?TvSeriesChangesChangesItemsValue $value = null;
    #[SerializedName('original_value')]
    private ?TvSeriesChangesChangesItemsOriginalValue $originalValue = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(?string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(?string $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getTime(): ?string
    {
        return $this->time;
    }

    public function setTime(?string $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getIso6391(): ?string
    {
        return $this->iso6391;
    }

    public function setIso6391(?string $iso6391): self
    {
        $this->iso6391 = $iso6391;

        return $this;
    }

    public function getIso31661(): ?string
    {
        return $this->iso31661;
    }

    public function setIso31661(?string $iso31661): self
    {
        $this->iso31661 = $iso31661;

        return $this;
    }

    public function getValue(): ?TvSeriesChangesChangesItemsValue
    {
        return $this->value;
    }

    public function setValue(?TvSeriesChangesChangesItemsValue $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getOriginalValue(): ?TvSeriesChangesChangesItemsOriginalValue
    {
        return $this->originalValue;
    }

    public function setOriginalValue(?TvSeriesChangesChangesItemsOriginalValue $originalValue): self
    {
        $this->originalValue = $originalValue;

        return $this;
    }
}