<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeriesChangesChangesItemsValue
{
    #[SerializedName('poster')]
    private ?TvSeriesChangesChangesItemsValuePoster $poster = null;

    public function getPoster(): ?TvSeriesChangesChangesItemsValuePoster
    {
        return $this->poster;
    }

    public function setPoster(?TvSeriesChangesChangesItemsValuePoster $poster): self
    {
        $this->poster = $poster;

        return $this;
    }
}