<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeasonAccountStatesResults
{
    #[SerializedName('id')]
    private ?int $id = null;
    #[SerializedName('episode_number')]
    private ?int $episodeNumber = null;
    #[SerializedName('rated')]
    private ?TvSeasonAccountStatesResultsRated $rated = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getEpisodeNumber(): ?int
    {
        return $this->episodeNumber;
    }

    public function setEpisodeNumber(?int $episodeNumber): self
    {
        $this->episodeNumber = $episodeNumber;

        return $this;
    }

    public function getRated(): ?TvSeasonAccountStatesResultsRated
    {
        return $this->rated;
    }

    public function setRated(?TvSeasonAccountStatesResultsRated $rated): self
    {
        $this->rated = $rated;

        return $this;
    }
}