<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeriesChanges
{
    /**
     * @var array<TvSeriesChangesChanges>
     */
    #[SerializedName('changes')]
    private array $changes = [];

    /**
     * @return array<TvSeriesChangesChanges>
     */
    public function getChanges(): array
    {
        return $this->changes;
    }

    /**
     * @param array<TvSeriesChangesChanges> $changes
     */
    public function setChanges(array $changes): self
    {
        $this->changes = $changes;

        return $this;
    }
}