<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeasonWatchProvidersResultsUS
{
    #[SerializedName('link')]
    private ?string $link = null;
    /**
     * @var array<TvSeasonWatchProvidersResultsUSBuy>
     */
    #[SerializedName('buy')]
    private array $buy = [];
    /**
     * @var array<TvSeasonWatchProvidersResultsUSFree>
     */
    #[SerializedName('free')]
    private array $free = [];
    /**
     * @var array<TvSeasonWatchProvidersResultsUSFlatrate>
     */
    #[SerializedName('flatrate')]
    private array $flatrate = [];

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    /**
     * @return array<TvSeasonWatchProvidersResultsUSBuy>
     */
    public function getBuy(): array
    {
        return $this->buy;
    }

    /**
     * @param array<TvSeasonWatchProvidersResultsUSBuy> $buy
     */
    public function setBuy(array $buy): self
    {
        $this->buy = $buy;

        return $this;
    }

    /**
     * @return array<TvSeasonWatchProvidersResultsUSFree>
     */
    public function getFree(): array
    {
        return $this->free;
    }

    /**
     * @param array<TvSeasonWatchProvidersResultsUSFree> $free
     */
    public function setFree(array $free): self
    {
        $this->free = $free;

        return $this;
    }

    /**
     * @return array<TvSeasonWatchProvidersResultsUSFlatrate>
     */
    public function getFlatrate(): array
    {
        return $this->flatrate;
    }

    /**
     * @param array<TvSeasonWatchProvidersResultsUSFlatrate> $flatrate
     */
    public function setFlatrate(array $flatrate): self
    {
        $this->flatrate = $flatrate;

        return $this;
    }
}