<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeasonVideos
{
    #[SerializedName('id')]
    private ?int $id = null;
    /**
     * @var array<TvSeasonVideosResults>
     */
    #[SerializedName('results')]
    private array $results = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return array<TvSeasonVideosResults>
     */
    public function getResults(): array
    {
        return $this->results;
    }

    /**
     * @param array<TvSeasonVideosResults> $results
     */
    public function setResults(array $results): self
    {
        $this->results = $results;

        return $this;
    }
}