<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeriesContentRatingsResults
{
    /**
     * @var array
     */
    #[SerializedName('descriptors')]
    private array $descriptors = [];
    #[SerializedName('iso_3166_1')]
    private ?string $iso31661 = null;
    #[SerializedName('rating')]
    private ?string $rating = null;

    /**
     * @return array
     */
    public function getDescriptors(): array
    {
        return $this->descriptors;
    }

    /**
     * @param array $descriptors
     */
    public function setDescriptors(array $descriptors): self
    {
        $this->descriptors = $descriptors;

        return $this;
    }

    public function getIso31661(): ?string
    {
        return $this->iso31661;
    }

    public function setIso31661(?string $iso31661): self
    {
        $this->iso31661 = $iso31661;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(?string $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
}