<?php

namespace App\Dto\Tmdb\Responses\Tv;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TvSeriesAggregateCreditsCrewJobs
{
    #[SerializedName('credit_id')]
    private ?string $creditId = null;
    #[SerializedName('job')]
    private ?string $job = null;
    #[SerializedName('episode_count')]
    private ?int $episodeCount = null;

    public function getCreditId(): ?string
    {
        return $this->creditId;
    }

    public function setCreditId(?string $creditId): self
    {
        $this->creditId = $creditId;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(?string $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getEpisodeCount(): ?int
    {
        return $this->episodeCount;
    }

    public function setEpisodeCount(?int $episodeCount): self
    {
        $this->episodeCount = $episodeCount;

        return $this;
    }
}