<?php

namespace App\Dto\Tmdb\Responses\Account;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class AccountDetailsAvatar
{
    #[SerializedName('gravatar')]
    private ?AccountDetailsAvatarGravatar $gravatar = null;
    #[SerializedName('tmdb')]
    private ?AccountDetailsAvatarTmdb $tmdb = null;

    public function getGravatar(): ?AccountDetailsAvatarGravatar
    {
        return $this->gravatar;
    }

    public function setGravatar(?AccountDetailsAvatarGravatar $gravatar): self
    {
        $this->gravatar = $gravatar;

        return $this;
    }

    public function getTmdb(): ?AccountDetailsAvatarTmdb
    {
        return $this->tmdb;
    }

    public function setTmdb(?AccountDetailsAvatarTmdb $tmdb): self
    {
        $this->tmdb = $tmdb;

        return $this;
    }
}