<?php

namespace App\Dto\Tmdb\Responses\Account;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class AccountDetailsAvatarGravatar
{
    #[SerializedName('hash')]
    private ?string $hash = null;

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(?string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }
}