<?php

namespace App\Dto\Tmdb\Clients\ConfigurationApi;

use App\Dto\Tmdb\Responses\Configuration\ConfigurationDetails;
use App\Dto\Tmdb\Responses\Configuration\ConfigurationCountries;
use App\Dto\Tmdb\Responses\Configuration\ConfigurationJobs;
use App\Dto\Tmdb\Responses\Configuration\ConfigurationLanguages;
use App\Dto\Tmdb\Responses\Configuration\ConfigurationTimezones;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface ConfigurationApiInterface
{
    /**
     * /3/configuration - Query the API configuration details.
     */
    public function configurationDetails(): ConfigurationDetails;

    /**
     * /3/configuration/countries - Get the list of countries (ISO 3166-1 tags) used throughout TMDB.
     * @return array<ConfigurationCountries>
     */
    public function configurationCountries(?string $language = 'en-US'): array;

    /**
     * /3/configuration/jobs - Get the list of the jobs and departments we use on TMDB.
     * @return array<ConfigurationJobs>
     */
    public function configurationJobs(): array;

    /**
     * /3/configuration/languages - Get the list of languages (ISO 639-1 tags) used throughout TMDB.
     * @return array<ConfigurationLanguages>
     */
    public function configurationLanguages(): array;

    /**
     * /3/configuration/primary_translations - Get a list of the officially supported translations on TMDB.
     * @return array<string>
     */
    public function configurationPrimaryTranslations(): array;

    /**
     * /3/configuration/timezones - Get the list of timezones used throughout TMDB.
     * @return array<ConfigurationTimezones>
     */
    public function configurationTimezones(): array;
}