<?php

namespace App\Dto\Tmdb\Responses\Movie;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class MovieAlternativeTitles
{
    #[SerializedName('id')]
    private ?int $id = null;
    /**
     * @var array<MovieAlternativeTitlesTitles>
     */
    #[SerializedName('titles')]
    private array $titles = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return array<MovieAlternativeTitlesTitles>
     */
    public function getTitles(): array
    {
        return $this->titles;
    }

    /**
     * @param array<MovieAlternativeTitlesTitles> $titles
     */
    public function setTitles(array $titles): self
    {
        $this->titles = $titles;

        return $this;
    }
}