<?php

namespace App\Dto\Tmdb\Responses\Movie;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class MovieKeywords
{
    #[SerializedName('id')]
    private ?int $id = null;
    /**
     * @var array<MovieKeywordsKeywords>
     */
    #[SerializedName('keywords')]
    private array $keywords = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return array<MovieKeywordsKeywords>
     */
    public function getKeywords(): array
    {
        return $this->keywords;
    }

    /**
     * @param array<MovieKeywordsKeywords> $keywords
     */
    public function setKeywords(array $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }
}