<?php

namespace App\Dto\Tmdb\Responses\Movie;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class MovieChangesChangesItemsValue
{
    #[SerializedName('poster')]
    private ?MovieChangesChangesItemsValuePoster $poster = null;

    public function getPoster(): ?MovieChangesChangesItemsValuePoster
    {
        return $this->poster;
    }

    public function setPoster(?MovieChangesChangesItemsValuePoster $poster): self
    {
        $this->poster = $poster;

        return $this;
    }
}