<?php

namespace App\Dto\Tmdb\Responses\Configuration;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class ConfigurationDetails
{
    #[SerializedName('images')]
    private ?ConfigurationDetailsImages $images = null;
    /**
     * @var array<string>
     */
    #[SerializedName('change_keys')]
    private array $changeKeys = [];

    public function getImages(): ?ConfigurationDetailsImages
    {
        return $this->images;
    }

    public function setImages(?ConfigurationDetailsImages $images): self
    {
        $this->images = $images;

        return $this;
    }

    /**
     * @return array<string>
     */
    public function getChangeKeys(): array
    {
        return $this->changeKeys;
    }

    /**
     * @param array<string> $changeKeys
     */
    public function setChangeKeys(array $changeKeys): self
    {
        $this->changeKeys = $changeKeys;

        return $this;
    }
}