<?php

namespace App\Dto\Tmdb\Clients\CreditApi;

use App\Dto\Tmdb\Responses\Credit\CreditDetails;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface CreditApiInterface
{
    /**
     * /3/credit/{credit_id} - Get a movie or TV credit details by ID.
     */
    public function creditDetails(string $creditId): CreditDetails;
}