<?php

namespace App\Dto\Tmdb\Clients\TrendingApi;

use App\Dto\Tmdb\Responses\Trending\TrendingAll;
use App\Dto\Tmdb\Responses\Trending\TrendingMovies;
use App\Dto\Tmdb\Responses\Trending\TrendingTv;
use App\Dto\Tmdb\Responses\Trending\TrendingPeople;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface TrendingApiInterface
{
    /**
     * /3/trending/all/{time_window} - Get the trending movies, TV shows and people.
     * @param ?string $language `ISO-639-1`-`ISO-3166-1` code
     */
    public function trendingAll(string $timeWindow, ?string $language = 'en-US'): TrendingAll;

    /**
     * /3/trending/movie/{time_window} - Get the trending movies on TMDB.
     * @param ?string $language `ISO-639-1`-`ISO-3166-1` code
     */
    public function trendingMovies(string $timeWindow, ?string $language = 'en-US'): TrendingMovies;

    /**
     * /3/trending/tv/{time_window} - Get the trending TV shows on TMDB.
     * @param ?string $language `ISO-639-1`-`ISO-3166-1` code
     */
    public function trendingTv(string $timeWindow, ?string $language = 'en-US'): TrendingTv;

    /**
     * /3/trending/person/{time_window} - Get the trending people on TMDB.
     * @param ?string $language `ISO-639-1`-`ISO-3166-1` code
     */
    public function trendingPeople(string $timeWindow, ?string $language = 'en-US'): TrendingPeople;
}