<?php

namespace App\Dto\Tmdb\Responses\Collection;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class CollectionDetails
{
    #[SerializedName('id')]
    private ?int $id = null;
    #[SerializedName('name')]
    private ?string $name = null;
    #[SerializedName('overview')]
    private ?string $overview = null;
    #[SerializedName('poster_path')]
    private ?string $posterPath = null;
    #[SerializedName('backdrop_path')]
    private ?string $backdropPath = null;
    /**
     * @var array<CollectionDetailsParts>
     */
    #[SerializedName('parts')]
    private array $parts = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->posterPath;
    }

    public function setPosterPath(?string $posterPath): self
    {
        $this->posterPath = $posterPath;

        return $this;
    }

    public function getBackdropPath(): ?string
    {
        return $this->backdropPath;
    }

    public function setBackdropPath(?string $backdropPath): self
    {
        $this->backdropPath = $backdropPath;

        return $this;
    }

    /**
     * @return array<CollectionDetailsParts>
     */
    public function getParts(): array
    {
        return $this->parts;
    }

    /**
     * @param array<CollectionDetailsParts> $parts
     */
    public function setParts(array $parts): self
    {
        $this->parts = $parts;

        return $this;
    }
}