<?php

namespace App\Dto\Tmdb\Clients\NetworkApi;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Contracts\Cache\CacheInterface;
use App\Dto\Tmdb\Responses\Network\NetworkDetails;
use App\Dto\Tmdb\Responses\Network\DetailsCopy;
use App\Dto\Tmdb\Responses\Network\AlternativeNamesCopy;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
readonly class NetworkApiClient implements NetworkApiInterface
{
    public function __construct(
        private HttpClientInterface $tmdbHttpClient,
        private DenormalizerInterface $denormalizer,
        private CacheInterface $redis,
    )
    {
    }

    /**
     * /3/network/{network_id}
     */
    public function networkDetails(int $networkId): NetworkDetails
    {
        $url = strtr('/3/network/{network_id}', [
            '{network_id}' => $networkId,
        ]);
        $query = [
        ];

        $cacheKey = md5($url.'?'.http_build_query($query));
        return $this->redis->get($cacheKey, function ($item) use ($url, $query) {
            $item->expiresAfter(10800);
            $response = $this->tmdbHttpClient->request('GET', $url, ['query' => $query]);
            return $this->denormalizer->denormalize($response->toArray(), NetworkDetails::class);
        });
    }

    /**
     * /3/network/{network_id}/alternative_names - Get the alternative names of a network.
     */
    public function detailsCopy(int $networkId): DetailsCopy
    {
        $url = strtr('/3/network/{network_id}/alternative_names', [
            '{network_id}' => $networkId,
        ]);
        $query = [
        ];

        $cacheKey = md5($url.'?'.http_build_query($query));
        return $this->redis->get($cacheKey, function ($item) use ($url, $query) {
            $item->expiresAfter(10800);
            $response = $this->tmdbHttpClient->request('GET', $url, ['query' => $query]);
            return $this->denormalizer->denormalize($response->toArray(), DetailsCopy::class);
        });
    }

    /**
     * /3/network/{network_id}/images - Get the TV network logos by id.
     */
    public function alternativeNamesCopy(int $networkId): AlternativeNamesCopy
    {
        $url = strtr('/3/network/{network_id}/images', [
            '{network_id}' => $networkId,
        ]);
        $query = [
        ];

        $cacheKey = md5($url.'?'.http_build_query($query));
        return $this->redis->get($cacheKey, function ($item) use ($url, $query) {
            $item->expiresAfter(10800);
            $response = $this->tmdbHttpClient->request('GET', $url, ['query' => $query]);
            return $this->denormalizer->denormalize($response->toArray(), AlternativeNamesCopy::class);
        });
    }
}