<?php

namespace App\Dto\Tmdb\Responses\Person;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class PersonLatestId
{
    #[SerializedName('adult')]
    private ?bool $adult = null;
    /**
     * @var array
     */
    #[SerializedName('also_known_as')]
    private array $alsoKnownAs = [];
    #[SerializedName('biography')]
    private ?string $biography = null;
    #[SerializedName('birthday')]
    private ?string $birthday = null;
    #[SerializedName('deathday')]
    private ?string $deathday = null;
    #[SerializedName('gender')]
    private ?int $gender = null;
    #[SerializedName('homepage')]
    private ?string $homepage = null;
    #[SerializedName('id')]
    private ?int $id = null;
    #[SerializedName('imdb_id')]
    private ?string $imdbId = null;
    #[SerializedName('known_for_department')]
    private ?string $knownForDepartment = null;
    #[SerializedName('name')]
    private ?string $name = null;
    #[SerializedName('place_of_birth')]
    private ?string $placeOfBirth = null;
    #[SerializedName('popularity')]
    private ?int $popularity = null;
    #[SerializedName('profile_path')]
    private ?string $profilePath = null;

    public function getAdult(): ?bool
    {
        return $this->adult;
    }

    public function setAdult(?bool $adult): self
    {
        $this->adult = $adult;

        return $this;
    }

    /**
     * @return array
     */
    public function getAlsoKnownAs(): array
    {
        return $this->alsoKnownAs;
    }

    /**
     * @param array $alsoKnownAs
     */
    public function setAlsoKnownAs(array $alsoKnownAs): self
    {
        $this->alsoKnownAs = $alsoKnownAs;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    public function getBirthday(): ?string
    {
        return $this->birthday;
    }

    public function setBirthday(?string $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getDeathday(): ?string
    {
        return $this->deathday;
    }

    public function setDeathday(?string $deathday): self
    {
        $this->deathday = $deathday;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(?int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getHomepage(): ?string
    {
        return $this->homepage;
    }

    public function setHomepage(?string $homepage): self
    {
        $this->homepage = $homepage;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getImdbId(): ?string
    {
        return $this->imdbId;
    }

    public function setImdbId(?string $imdbId): self
    {
        $this->imdbId = $imdbId;

        return $this;
    }

    public function getKnownForDepartment(): ?string
    {
        return $this->knownForDepartment;
    }

    public function setKnownForDepartment(?string $knownForDepartment): self
    {
        $this->knownForDepartment = $knownForDepartment;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPlaceOfBirth(): ?string
    {
        return $this->placeOfBirth;
    }

    public function setPlaceOfBirth(?string $placeOfBirth): self
    {
        $this->placeOfBirth = $placeOfBirth;

        return $this;
    }

    public function getPopularity(): ?int
    {
        return $this->popularity;
    }

    public function setPopularity(?int $popularity): self
    {
        $this->popularity = $popularity;

        return $this;
    }

    public function getProfilePath(): ?string
    {
        return $this->profilePath;
    }

    public function setProfilePath(?string $profilePath): self
    {
        $this->profilePath = $profilePath;

        return $this;
    }
}