<?php

namespace App\Dto\Tmdb\Responses\Person;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class TranslationsTranslationsData
{
    #[SerializedName('biography')]
    private ?string $biography = null;

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }
}