<?php

namespace App\Dto\Tmdb\Responses\Certification;

use Symfony\Component\Serializer\Annotation\SerializedName;
use Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter;
use Symfony\Component\Serializer\Normalizer\ArrayDenormalizer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class CertificationsTvListCertifications
{
    /**
     * @var array<CertificationsTvListCertificationsAU>
     */
    #[SerializedName('AU')]
    private array $AU = [];
    /**
     * @var array<CertificationsTvListCertificationsBR>
     */
    #[SerializedName('BR')]
    private array $BR = [];
    /**
     * @var array<CertificationsTvListCertificationsCA>
     */
    #[SerializedName('CA')]
    private array $CA = [];
    /**
     * @var array<CertificationsTvListCertificationsCAQC>
     */
    #[SerializedName('CA-QC')]
    private array $CA_QC = [];
    /**
     * @var array<CertificationsTvListCertificationsDE>
     */
    #[SerializedName('DE')]
    private array $DE = [];
    /**
     * @var array<CertificationsTvListCertificationsES>
     */
    #[SerializedName('ES')]
    private array $ES = [];
    /**
     * @var array<CertificationsTvListCertificationsFR>
     */
    #[SerializedName('FR')]
    private array $FR = [];
    /**
     * @var array<CertificationsTvListCertificationsGB>
     */
    #[SerializedName('GB')]
    private array $GB = [];
    /**
     * @var array<CertificationsTvListCertificationsHU>
     */
    #[SerializedName('HU')]
    private array $HU = [];
    /**
     * @var array<CertificationsTvListCertificationsKR>
     */
    #[SerializedName('KR')]
    private array $KR = [];
    /**
     * @var array<CertificationsTvListCertificationsLT>
     */
    #[SerializedName('LT')]
    private array $LT = [];
    /**
     * @var array<CertificationsTvListCertificationsNL>
     */
    #[SerializedName('NL')]
    private array $NL = [];
    /**
     * @var array<CertificationsTvListCertificationsPH>
     */
    #[SerializedName('PH')]
    private array $PH = [];
    /**
     * @var array<CertificationsTvListCertificationsPT>
     */
    #[SerializedName('PT')]
    private array $PT = [];
    /**
     * @var array<CertificationsTvListCertificationsRU>
     */
    #[SerializedName('RU')]
    private array $RU = [];
    /**
     * @var array<CertificationsTvListCertificationsSK>
     */
    #[SerializedName('SK')]
    private array $SK = [];
    /**
     * @var array<CertificationsTvListCertificationsTH>
     */
    #[SerializedName('TH')]
    private array $TH = [];
    /**
     * @var array<CertificationsTvListCertificationsUS>
     */
    #[SerializedName('US')]
    private array $US = [];
    /**
     * @var array<CertificationsTvListCertificationsIT>
     */
    #[SerializedName('IT')]
    private array $IT = [];
    /**
     * @var array<CertificationsTvListCertificationsFI>
     */
    #[SerializedName('FI')]
    private array $FI = [];
    /**
     * @var array<CertificationsTvListCertificationsMY>
     */
    #[SerializedName('MY')]
    private array $MY = [];
    /**
     * @var array<CertificationsTvListCertificationsNZ>
     */
    #[SerializedName('NZ')]
    private array $NZ = [];
    /**
     * @var array<CertificationsTvListCertificationsNO>
     */
    #[SerializedName('NO')]
    private array $NO = [];
    /**
     * @var array<CertificationsTvListCertificationsBG>
     */
    #[SerializedName('BG')]
    private array $BG = [];
    /**
     * @var array<CertificationsTvListCertificationsMX>
     */
    #[SerializedName('MX')]
    private array $MX = [];
    /**
     * @var array<CertificationsTvListCertificationsIN>
     */
    #[SerializedName('IN')]
    private array $IN = [];
    /**
     * @var array<CertificationsTvListCertificationsDK>
     */
    #[SerializedName('DK')]
    private array $DK = [];
    /**
     * @var array<CertificationsTvListCertificationsSE>
     */
    #[SerializedName('SE')]
    private array $SE = [];
    /**
     * @var array<CertificationsTvListCertificationsID>
     */
    #[SerializedName('ID')]
    private array $ID = [];
    /**
     * @var array<CertificationsTvListCertificationsTR>
     */
    #[SerializedName('TR')]
    private array $TR = [];
    /**
     * @var array<CertificationsTvListCertificationsAR>
     */
    #[SerializedName('AR')]
    private array $AR = [];
    /**
     * @var array<CertificationsTvListCertificationsPL>
     */
    #[SerializedName('PL')]
    private array $PL = [];
    /**
     * @var array<CertificationsTvListCertificationsMA>
     */
    #[SerializedName('MA')]
    private array $MA = [];
    /**
     * @var array<CertificationsTvListCertificationsGR>
     */
    #[SerializedName('GR')]
    private array $GR = [];
    /**
     * @var array<CertificationsTvListCertificationsIL>
     */
    #[SerializedName('IL')]
    private array $IL = [];
    /**
     * @var array<CertificationsTvListCertificationsTW>
     */
    #[SerializedName('TW')]
    private array $TW = [];
    /**
     * @var array<CertificationsTvListCertificationsZA>
     */
    #[SerializedName('ZA')]
    private array $ZA = [];
    /**
     * @var array<CertificationsTvListCertificationsSG>
     */
    #[SerializedName('SG')]
    private array $SG = [];
    /**
     * @var array<CertificationsTvListCertificationsPR>
     */
    #[SerializedName('PR')]
    private array $PR = [];
    /**
     * @var array<CertificationsTvListCertificationsVI>
     */
    #[SerializedName('VI')]
    private array $VI = [];

    public static function fromArray(array $data = []): self
    {
        $serializer = new Serializer([new ObjectNormalizer(nameConverter: new CamelCaseToSnakeCaseNameConverter()), new ArrayDenormalizer()]);
        return $serializer->denormalize($data, self::class);
    }

    public function toArray(): array
    {
        $serializer = new Serializer([new ObjectNormalizer(nameConverter: new CamelCaseToSnakeCaseNameConverter()), new ArrayDenormalizer()]);
        return $serializer->normalize($this);
    }

    /**
     * @return array<CertificationsTvListCertificationsAU>
     */
    public function getAU(): array
    {
        return $this->AU;
    }

    /**
     * @param array<CertificationsTvListCertificationsAU> $AU
     */
    public function setAU(array $AU): self
    {
        $this->AU = $AU;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsBR>
     */
    public function getBR(): array
    {
        return $this->BR;
    }

    /**
     * @param array<CertificationsTvListCertificationsBR> $BR
     */
    public function setBR(array $BR): self
    {
        $this->BR = $BR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsCA>
     */
    public function getCA(): array
    {
        return $this->CA;
    }

    /**
     * @param array<CertificationsTvListCertificationsCA> $CA
     */
    public function setCA(array $CA): self
    {
        $this->CA = $CA;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsCAQC>
     */
    public function getCA_QC(): array
    {
        return $this->CA_QC;
    }

    /**
     * @param array<CertificationsTvListCertificationsCAQC> $CA_QC
     */
    public function setCA_QC(array $CA_QC): self
    {
        $this->CA_QC = $CA_QC;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsDE>
     */
    public function getDE(): array
    {
        return $this->DE;
    }

    /**
     * @param array<CertificationsTvListCertificationsDE> $DE
     */
    public function setDE(array $DE): self
    {
        $this->DE = $DE;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsES>
     */
    public function getES(): array
    {
        return $this->ES;
    }

    /**
     * @param array<CertificationsTvListCertificationsES> $ES
     */
    public function setES(array $ES): self
    {
        $this->ES = $ES;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsFR>
     */
    public function getFR(): array
    {
        return $this->FR;
    }

    /**
     * @param array<CertificationsTvListCertificationsFR> $FR
     */
    public function setFR(array $FR): self
    {
        $this->FR = $FR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsGB>
     */
    public function getGB(): array
    {
        return $this->GB;
    }

    /**
     * @param array<CertificationsTvListCertificationsGB> $GB
     */
    public function setGB(array $GB): self
    {
        $this->GB = $GB;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsHU>
     */
    public function getHU(): array
    {
        return $this->HU;
    }

    /**
     * @param array<CertificationsTvListCertificationsHU> $HU
     */
    public function setHU(array $HU): self
    {
        $this->HU = $HU;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsKR>
     */
    public function getKR(): array
    {
        return $this->KR;
    }

    /**
     * @param array<CertificationsTvListCertificationsKR> $KR
     */
    public function setKR(array $KR): self
    {
        $this->KR = $KR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsLT>
     */
    public function getLT(): array
    {
        return $this->LT;
    }

    /**
     * @param array<CertificationsTvListCertificationsLT> $LT
     */
    public function setLT(array $LT): self
    {
        $this->LT = $LT;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsNL>
     */
    public function getNL(): array
    {
        return $this->NL;
    }

    /**
     * @param array<CertificationsTvListCertificationsNL> $NL
     */
    public function setNL(array $NL): self
    {
        $this->NL = $NL;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsPH>
     */
    public function getPH(): array
    {
        return $this->PH;
    }

    /**
     * @param array<CertificationsTvListCertificationsPH> $PH
     */
    public function setPH(array $PH): self
    {
        $this->PH = $PH;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsPT>
     */
    public function getPT(): array
    {
        return $this->PT;
    }

    /**
     * @param array<CertificationsTvListCertificationsPT> $PT
     */
    public function setPT(array $PT): self
    {
        $this->PT = $PT;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsRU>
     */
    public function getRU(): array
    {
        return $this->RU;
    }

    /**
     * @param array<CertificationsTvListCertificationsRU> $RU
     */
    public function setRU(array $RU): self
    {
        $this->RU = $RU;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsSK>
     */
    public function getSK(): array
    {
        return $this->SK;
    }

    /**
     * @param array<CertificationsTvListCertificationsSK> $SK
     */
    public function setSK(array $SK): self
    {
        $this->SK = $SK;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsTH>
     */
    public function getTH(): array
    {
        return $this->TH;
    }

    /**
     * @param array<CertificationsTvListCertificationsTH> $TH
     */
    public function setTH(array $TH): self
    {
        $this->TH = $TH;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsUS>
     */
    public function getUS(): array
    {
        return $this->US;
    }

    /**
     * @param array<CertificationsTvListCertificationsUS> $US
     */
    public function setUS(array $US): self
    {
        $this->US = $US;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsIT>
     */
    public function getIT(): array
    {
        return $this->IT;
    }

    /**
     * @param array<CertificationsTvListCertificationsIT> $IT
     */
    public function setIT(array $IT): self
    {
        $this->IT = $IT;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsFI>
     */
    public function getFI(): array
    {
        return $this->FI;
    }

    /**
     * @param array<CertificationsTvListCertificationsFI> $FI
     */
    public function setFI(array $FI): self
    {
        $this->FI = $FI;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsMY>
     */
    public function getMY(): array
    {
        return $this->MY;
    }

    /**
     * @param array<CertificationsTvListCertificationsMY> $MY
     */
    public function setMY(array $MY): self
    {
        $this->MY = $MY;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsNZ>
     */
    public function getNZ(): array
    {
        return $this->NZ;
    }

    /**
     * @param array<CertificationsTvListCertificationsNZ> $NZ
     */
    public function setNZ(array $NZ): self
    {
        $this->NZ = $NZ;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsNO>
     */
    public function getNO(): array
    {
        return $this->NO;
    }

    /**
     * @param array<CertificationsTvListCertificationsNO> $NO
     */
    public function setNO(array $NO): self
    {
        $this->NO = $NO;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsBG>
     */
    public function getBG(): array
    {
        return $this->BG;
    }

    /**
     * @param array<CertificationsTvListCertificationsBG> $BG
     */
    public function setBG(array $BG): self
    {
        $this->BG = $BG;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsMX>
     */
    public function getMX(): array
    {
        return $this->MX;
    }

    /**
     * @param array<CertificationsTvListCertificationsMX> $MX
     */
    public function setMX(array $MX): self
    {
        $this->MX = $MX;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsIN>
     */
    public function getIN(): array
    {
        return $this->IN;
    }

    /**
     * @param array<CertificationsTvListCertificationsIN> $IN
     */
    public function setIN(array $IN): self
    {
        $this->IN = $IN;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsDK>
     */
    public function getDK(): array
    {
        return $this->DK;
    }

    /**
     * @param array<CertificationsTvListCertificationsDK> $DK
     */
    public function setDK(array $DK): self
    {
        $this->DK = $DK;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsSE>
     */
    public function getSE(): array
    {
        return $this->SE;
    }

    /**
     * @param array<CertificationsTvListCertificationsSE> $SE
     */
    public function setSE(array $SE): self
    {
        $this->SE = $SE;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsID>
     */
    public function getID(): array
    {
        return $this->ID;
    }

    /**
     * @param array<CertificationsTvListCertificationsID> $ID
     */
    public function setID(array $ID): self
    {
        $this->ID = $ID;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsTR>
     */
    public function getTR(): array
    {
        return $this->TR;
    }

    /**
     * @param array<CertificationsTvListCertificationsTR> $TR
     */
    public function setTR(array $TR): self
    {
        $this->TR = $TR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsAR>
     */
    public function getAR(): array
    {
        return $this->AR;
    }

    /**
     * @param array<CertificationsTvListCertificationsAR> $AR
     */
    public function setAR(array $AR): self
    {
        $this->AR = $AR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsPL>
     */
    public function getPL(): array
    {
        return $this->PL;
    }

    /**
     * @param array<CertificationsTvListCertificationsPL> $PL
     */
    public function setPL(array $PL): self
    {
        $this->PL = $PL;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsMA>
     */
    public function getMA(): array
    {
        return $this->MA;
    }

    /**
     * @param array<CertificationsTvListCertificationsMA> $MA
     */
    public function setMA(array $MA): self
    {
        $this->MA = $MA;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsGR>
     */
    public function getGR(): array
    {
        return $this->GR;
    }

    /**
     * @param array<CertificationsTvListCertificationsGR> $GR
     */
    public function setGR(array $GR): self
    {
        $this->GR = $GR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsIL>
     */
    public function getIL(): array
    {
        return $this->IL;
    }

    /**
     * @param array<CertificationsTvListCertificationsIL> $IL
     */
    public function setIL(array $IL): self
    {
        $this->IL = $IL;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsTW>
     */
    public function getTW(): array
    {
        return $this->TW;
    }

    /**
     * @param array<CertificationsTvListCertificationsTW> $TW
     */
    public function setTW(array $TW): self
    {
        $this->TW = $TW;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsZA>
     */
    public function getZA(): array
    {
        return $this->ZA;
    }

    /**
     * @param array<CertificationsTvListCertificationsZA> $ZA
     */
    public function setZA(array $ZA): self
    {
        $this->ZA = $ZA;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsSG>
     */
    public function getSG(): array
    {
        return $this->SG;
    }

    /**
     * @param array<CertificationsTvListCertificationsSG> $SG
     */
    public function setSG(array $SG): self
    {
        $this->SG = $SG;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsPR>
     */
    public function getPR(): array
    {
        return $this->PR;
    }

    /**
     * @param array<CertificationsTvListCertificationsPR> $PR
     */
    public function setPR(array $PR): self
    {
        $this->PR = $PR;

        return $this;
    }

    /**
     * @return array<CertificationsTvListCertificationsVI>
     */
    public function getVI(): array
    {
        return $this->VI;
    }

    /**
     * @param array<CertificationsTvListCertificationsVI> $VI
     */
    public function setVI(array $VI): self
    {
        $this->VI = $VI;

        return $this;
    }
}