<?php

namespace App\Dto\Tmdb\Responses\Certification;

use Symfony\Component\Serializer\Annotation\SerializedName;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
class CertificationsTvList
{
    #[SerializedName('certifications')]
    private ?CertificationsTvListCertifications $certifications = null;

    public function getCertifications(): ?CertificationsTvListCertifications
    {
        return $this->certifications;
    }

    public function setCertifications(?CertificationsTvListCertifications $certifications): self
    {
        $this->certifications = $certifications;

        return $this;
    }
}