<?php

namespace App\Dto\Tmdb\Clients\GenreApi;

use App\Dto\Tmdb\Responses\Genre\GenreMovieList;
use App\Dto\Tmdb\Responses\Genre\GenreTvList;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface GenreApiInterface
{
    /**
     * /3/genre/movie/list - Get the list of official genres for movies.
     */
    public function genreMovieList(?string $language = 'en'): GenreMovieList;

    /**
     * /3/genre/tv/list - Get the list of official genres for TV shows.
     */
    public function genreTvList(?string $language = 'en'): GenreTvList;
}