<?php

namespace App\Dto\Tmdb\Clients\GenreApi;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Contracts\Cache\CacheInterface;
use App\Dto\Tmdb\Responses\Genre\GenreMovieList;
use App\Dto\Tmdb\Responses\Genre\GenreTvList;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
readonly class GenreApiClient implements GenreApiInterface
{
    public function __construct(
        private HttpClientInterface $tmdbHttpClient,
        private DenormalizerInterface $denormalizer,
        private CacheInterface $redis,
    )
    {
    }

    /**
     * /3/genre/movie/list - Get the list of official genres for movies.
     */
    public function genreMovieList(?string $language = 'en'): GenreMovieList
    {
        $url = strtr('/3/genre/movie/list', [
        ]);
        $query = [
            'language' => $language,
        ];

        $cacheKey = md5($url.'?'.http_build_query($query));
        return $this->redis->get($cacheKey, function ($item) use ($url, $query) {
            $item->expiresAfter(10800);
            $response = $this->tmdbHttpClient->request('GET', $url, ['query' => $query]);
            return $this->denormalizer->denormalize($response->toArray(), GenreMovieList::class);
        });
    }

    /**
     * /3/genre/tv/list - Get the list of official genres for TV shows.
     */
    public function genreTvList(?string $language = 'en'): GenreTvList
    {
        $url = strtr('/3/genre/tv/list', [
        ]);
        $query = [
            'language' => $language,
        ];

        $cacheKey = md5($url.'?'.http_build_query($query));
        return $this->redis->get($cacheKey, function ($item) use ($url, $query) {
            $item->expiresAfter(10800);
            $response = $this->tmdbHttpClient->request('GET', $url, ['query' => $query]);
            return $this->denormalizer->denormalize($response->toArray(), GenreTvList::class);
        });
    }
}