<?php

namespace App\Dto\Tmdb\Clients\PersonApi;

use App\Dto\Tmdb\Responses\Person\PersonDetails;
use App\Dto\Tmdb\Responses\Person\PersonChanges;
use App\Dto\Tmdb\Responses\Person\PersonImages;
use App\Dto\Tmdb\Responses\Person\PersonMovieCredits;
use App\Dto\Tmdb\Responses\Person\PersonTvCredits;
use App\Dto\Tmdb\Responses\Person\PersonCombinedCredits;
use App\Dto\Tmdb\Responses\Person\PersonExternalIds;
use App\Dto\Tmdb\Responses\Person\PersonTaggedImages;
use App\Dto\Tmdb\Responses\Person\Translations;
use App\Dto\Tmdb\Responses\Person\PersonPopularList;
use App\Dto\Tmdb\Responses\Person\ChangesPeopleList;
use App\Dto\Tmdb\Responses\Person\PersonLatestId;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface PersonApiInterface
{
    /**
     * /3/person/{person_id} - Query the top level details of a person.
     * @param ?string $appendToResponse comma separated list of endpoints within this namespace, 20 items max
     */
    public function personDetails(int $personId, ?string $language = 'en-US', ?string $appendToResponse = null): PersonDetails;

    /**
     * /3/person/{person_id}/changes - Get the recent changes for a person.
     */
    public function personChanges(int $personId, ?string $startDate = null, ?int $page = 1, ?string $endDate = null): PersonChanges;

    /**
     * /3/person/{person_id}/images - Get the profile images that belong to a person.
     */
    public function personImages(int $personId): PersonImages;

    /**
     * /3/person/{person_id}/movie_credits - Get the movie credits for a person.
     */
    public function personMovieCredits(int $personId, ?string $language = 'en-US'): PersonMovieCredits;

    /**
     * /3/person/{person_id}/tv_credits - Get the TV credits that belong to a person.
     */
    public function personTvCredits(int $personId, ?string $language = 'en-US'): PersonTvCredits;

    /**
     * /3/person/{person_id}/combined_credits - Get the combined movie and TV credits that belong to a person.
     */
    public function personCombinedCredits(string $personId, ?string $language = 'en-US'): PersonCombinedCredits;

    /**
     * /3/person/{person_id}/external_ids - Get the external ID's that belong to a person.
     */
    public function personExternalIds(int $personId): PersonExternalIds;

    /**
     * /3/person/{person_id}/tagged_images - Get the tagged images for a person.
     */
    public function personTaggedImages(int $personId, ?int $page = 1): PersonTaggedImages;

    /**
     * /3/person/{person_id}/translations - Get the translations that belong to a person.
     */
    public function translations(int $personId): Translations;

    /**
     * /3/person/popular - Get a list of people ordered by popularity.
     */
    public function personPopularList(?int $page = 1, ?string $language = 'en-US'): PersonPopularList;

    /**
     * /3/person/changes
     */
    public function changesPeopleList(?int $page = 1, ?string $startDate = null, ?string $endDate = null): ChangesPeopleList;

    /**
     * /3/person/latest - Get the newest created person. This is a live response and will continuously change.
     */
    public function personLatestId(): PersonLatestId;
}