<?php

namespace App\Dto\Tmdb\Clients\TvApi;

use App\Dto\Tmdb\Responses\Tv\TvSeriesDetails;
use App\Dto\Tmdb\Responses\Tv\TvSeasonDetails;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeDetails;
use App\Dto\Tmdb\Responses\Tv\TvSeriesImages;
use App\Dto\Tmdb\Responses\Tv\TvSeasonImages;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeImages;
use App\Dto\Tmdb\Responses\Tv\TvSeriesAccountStates;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeAccountStates;
use App\Dto\Tmdb\Responses\Tv\TvSeriesChanges;
use App\Dto\Tmdb\Responses\Tv\TvSeriesAiringTodayList;
use App\Dto\Tmdb\Responses\Tv\TvSeriesOnTheAirList;
use App\Dto\Tmdb\Responses\Tv\TvSeriesPopularList;
use App\Dto\Tmdb\Responses\Tv\TvSeriesTopRatedList;
use App\Dto\Tmdb\Responses\Tv\TvSeriesLatestId;
use App\Dto\Tmdb\Responses\Tv\TvSeriesAggregateCredits;
use App\Dto\Tmdb\Responses\Tv\TvSeriesAlternativeTitles;
use App\Dto\Tmdb\Responses\Tv\TvSeriesContentRatings;
use App\Dto\Tmdb\Responses\Tv\TvSeriesCredits;
use App\Dto\Tmdb\Responses\Tv\TvSeriesEpisodeGroups;
use App\Dto\Tmdb\Responses\Tv\TvSeriesExternalIds;
use App\Dto\Tmdb\Responses\Tv\TvSeriesKeywords;
use App\Dto\Tmdb\Responses\Tv\TvSeriesRecommendations;
use App\Dto\Tmdb\Responses\Tv\TvSeriesReviews;
use App\Dto\Tmdb\Responses\Tv\TvSeriesScreenedTheatrically;
use App\Dto\Tmdb\Responses\Tv\TvSeriesSimilar;
use App\Dto\Tmdb\Responses\Tv\TvSeriesTranslations;
use App\Dto\Tmdb\Responses\Tv\TvSeriesVideos;
use App\Dto\Tmdb\Responses\Tv\TvSeriesWatchProviders;
use App\Dto\Tmdb\Responses\Tv\TvSeasonAccountStates;
use App\Dto\Tmdb\Responses\Tv\TvSeasonAggregateCredits;
use App\Dto\Tmdb\Responses\Tv\TvSeasonChangesById;
use App\Dto\Tmdb\Responses\Tv\TvSeasonCredits;
use App\Dto\Tmdb\Responses\Tv\TvSeasonExternalIds;
use App\Dto\Tmdb\Responses\Tv\TvSeasonTranslations;
use App\Dto\Tmdb\Responses\Tv\TvSeasonVideos;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeCredits;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeExternalIds;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeTranslations;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeVideos;
use App\Dto\Tmdb\Responses\Tv\ChangesTvList;
use App\Dto\Tmdb\Responses\Tv\TvSeasonWatchProviders;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeChangesById;
use App\Dto\Tmdb\Responses\Tv\TvEpisodeGroupDetails;
use App\Dto\Tmdb\Responses\Tv\ListsCopy;

/**
 * This class was auto generated by the TMDB DTO Generator.
 * Do not edit this file manually!
 */
interface TvApiInterface
{
    /**
     * /3/tv/{series_id} - Get the details of a TV show.
     * @param ?string $appendToResponse comma separated list of endpoints within this namespace, 20 items max
     */
    public function tvSeriesDetails(int $seriesId, ?string $language = 'en-US', ?string $appendToResponse = null): TvSeriesDetails;

    /**
     * /3/tv/{series_id}/season/{season_number} - Query the details of a TV season.
     * @param ?string $appendToResponse comma separated list of endpoints within this namespace, 20 items max
     */
    public function tvSeasonDetails(int $seasonNumber, int $seriesId, ?string $language = 'en-US', ?string $appendToResponse = null): TvSeasonDetails;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number} - Query the details of a TV episode.
     * @param ?string $appendToResponse comma separated list of endpoints within this namespace, 20 items max
     */
    public function tvEpisodeDetails(int $seasonNumber, int $episodeNumber, int $seriesId, ?string $language = 'en-US', ?string $appendToResponse = null): TvEpisodeDetails;

    /**
     * /3/tv/{series_id}/images - Get the images that belong to a TV series.
     * @param ?string $includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
     */
    public function tvSeriesImages(int $seriesId, ?string $language = null, ?string $includeImageLanguage = null): TvSeriesImages;

    /**
     * /3/tv/{series_id}/season/{season_number}/images - Get the images that belong to a TV season.
     * @param ?string $includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
     */
    public function tvSeasonImages(int $seasonNumber, int $seriesId, ?string $language = null, ?string $includeImageLanguage = null): TvSeasonImages;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/images - Get the images that belong to a TV episode.
     * @param ?string $includeImageLanguage specify a comma separated list of ISO-639-1 values to query, for example: `en,null`
     */
    public function tvEpisodeImages(int $episodeNumber, int $seasonNumber, int $seriesId, ?string $language = null, ?string $includeImageLanguage = null): TvEpisodeImages;

    /**
     * /3/tv/{series_id}/account_states - Get the rating, watchlist and favourite status.
     */
    public function tvSeriesAccountStates(int $seriesId, ?string $guestSessionId = null, ?string $sessionId = null): TvSeriesAccountStates;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states - Get the rating, watchlist and favourite status.
     */
    public function tvEpisodeAccountStates(int $episodeNumber, int $seasonNumber, int $seriesId, ?string $guestSessionId = null, ?string $sessionId = null): TvEpisodeAccountStates;

    /**
     * /3/tv/{series_id}/changes - Get the recent changes for a TV show.
     */
    public function tvSeriesChanges(int $seriesId, ?string $startDate = null, ?int $page = 1, ?string $endDate = null): TvSeriesChanges;

    /**
     * /3/tv/airing_today - Get a list of TV shows airing today.
     */
    public function tvSeriesAiringTodayList(?int $page = 1, ?string $timezone = null, ?string $language = 'en-US'): TvSeriesAiringTodayList;

    /**
     * /3/tv/on_the_air - Get a list of TV shows that air in the next 7 days.
     */
    public function tvSeriesOnTheAirList(?int $page = 1, ?string $timezone = null, ?string $language = 'en-US'): TvSeriesOnTheAirList;

    /**
     * /3/tv/popular - Get a list of TV shows ordered by popularity.
     */
    public function tvSeriesPopularList(?int $page = 1, ?string $language = 'en-US'): TvSeriesPopularList;

    /**
     * /3/tv/top_rated - Get a list of TV shows ordered by rating.
     */
    public function tvSeriesTopRatedList(?int $page = 1, ?string $language = 'en-US'): TvSeriesTopRatedList;

    /**
     * /3/tv/latest - Get the newest TV show ID.
     */
    public function tvSeriesLatestId(): TvSeriesLatestId;

    /**
     * /3/tv/{series_id}/aggregate_credits - Get the aggregate credits (cast and crew) that have been added to a TV show.
     */
    public function tvSeriesAggregateCredits(int $seriesId, ?string $language = 'en-US'): TvSeriesAggregateCredits;

    /**
     * /3/tv/{series_id}/alternative_titles - Get the alternative titles that have been added to a TV show.
     */
    public function tvSeriesAlternativeTitles(int $seriesId): TvSeriesAlternativeTitles;

    /**
     * /3/tv/{series_id}/content_ratings - Get the content ratings that have been added to a TV show.
     */
    public function tvSeriesContentRatings(int $seriesId): TvSeriesContentRatings;

    /**
     * /3/tv/{series_id}/credits - Get the latest season credits of a TV show.
     */
    public function tvSeriesCredits(int $seriesId, ?string $language = 'en-US'): TvSeriesCredits;

    /**
     * /3/tv/{series_id}/episode_groups - Get the episode groups that have been added to a TV show.
     */
    public function tvSeriesEpisodeGroups(int $seriesId): TvSeriesEpisodeGroups;

    /**
     * /3/tv/{series_id}/external_ids - Get a list of external IDs that have been added to a TV show.
     */
    public function tvSeriesExternalIds(int $seriesId): TvSeriesExternalIds;

    /**
     * /3/tv/{series_id}/keywords - Get a list of keywords that have been added to a TV show.
     */
    public function tvSeriesKeywords(int $seriesId): TvSeriesKeywords;

    /**
     * /3/tv/{series_id}/recommendations
     */
    public function tvSeriesRecommendations(int $seriesId, ?int $page = 1, ?string $language = 'en-US'): TvSeriesRecommendations;

    /**
     * /3/tv/{series_id}/reviews - Get the reviews that have been added to a TV show.
     */
    public function tvSeriesReviews(int $seriesId, ?int $page = 1, ?string $language = 'en-US'): TvSeriesReviews;

    /**
     * /3/tv/{series_id}/screened_theatrically - Get the seasons and episodes that have screened theatrically.
     */
    public function tvSeriesScreenedTheatrically(int $seriesId): TvSeriesScreenedTheatrically;

    /**
     * /3/tv/{series_id}/similar - Get the similar TV shows.
     */
    public function tvSeriesSimilar(string $seriesId, ?int $page = 1, ?string $language = 'en-US'): TvSeriesSimilar;

    /**
     * /3/tv/{series_id}/translations - Get the translations that have been added to a TV show.
     */
    public function tvSeriesTranslations(int $seriesId): TvSeriesTranslations;

    /**
     * /3/tv/{series_id}/videos - Get the videos that belong to a TV show.
     * @param ?string $includeVideoLanguage filter the list results by language, supports more than one value by using a comma
     */
    public function tvSeriesVideos(int $seriesId, ?string $language = 'en-US', ?string $includeVideoLanguage = null): TvSeriesVideos;

    /**
     * /3/tv/{series_id}/watch/providers - Get the list of streaming providers we have for a TV show.
     */
    public function tvSeriesWatchProviders(int $seriesId): TvSeriesWatchProviders;

    /**
     * /3/tv/{series_id}/season/{season_number}/account_states - Get the rating, watchlist and favourite status.
     */
    public function tvSeasonAccountStates(int $seasonNumber, int $seriesId, ?string $guestSessionId = null, ?string $sessionId = null): TvSeasonAccountStates;

    /**
     * /3/tv/{series_id}/season/{season_number}/aggregate_credits - Get the aggregate credits (cast and crew) that have been added to a TV season.
     */
    public function tvSeasonAggregateCredits(int $seasonNumber, int $seriesId, ?string $language = 'en-US'): TvSeasonAggregateCredits;

    /**
     * /3/tv/season/{season_id}/changes - Get the recent changes for a TV season.
     */
    public function tvSeasonChangesById(int $seasonId, ?int $page = 1, ?string $startDate = null, ?string $endDate = null): TvSeasonChangesById;

    /**
     * /3/tv/{series_id}/season/{season_number}/credits
     */
    public function tvSeasonCredits(int $seasonNumber, int $seriesId, ?string $language = 'en-US'): TvSeasonCredits;

    /**
     * /3/tv/{series_id}/season/{season_number}/external_ids - Get a list of external IDs that have been added to a TV season.
     */
    public function tvSeasonExternalIds(int $seasonNumber, int $seriesId): TvSeasonExternalIds;

    /**
     * /3/tv/{series_id}/season/{season_number}/translations - Get the translations for a TV season.
     */
    public function tvSeasonTranslations(int $seasonNumber, int $seriesId): TvSeasonTranslations;

    /**
     * /3/tv/{series_id}/season/{season_number}/videos - Get the videos that belong to a TV season.
     * @param ?string $includeVideoLanguage filter the list results by language, supports more than one value by using a comma
     */
    public function tvSeasonVideos(int $seasonNumber, int $seriesId, ?string $language = 'en-US', ?string $includeVideoLanguage = null): TvSeasonVideos;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/credits
     */
    public function tvEpisodeCredits(int $episodeNumber, int $seasonNumber, int $seriesId, ?string $language = 'en-US'): TvEpisodeCredits;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/external_ids - Get a list of external IDs that have been added to a TV episode.
     */
    public function tvEpisodeExternalIds(int $seasonNumber, string $episodeNumber, int $seriesId): TvEpisodeExternalIds;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/translations - Get the translations that have been added to a TV episode.
     */
    public function tvEpisodeTranslations(int $seasonNumber, int $episodeNumber, int $seriesId): TvEpisodeTranslations;

    /**
     * /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/videos - Get the videos that belong to a TV episode.
     * @param ?string $includeVideoLanguage filter the list results by language, supports more than one value by using a comma
     */
    public function tvEpisodeVideos(int $episodeNumber, int $seasonNumber, int $seriesId, ?string $language = 'en-US', ?string $includeVideoLanguage = null): TvEpisodeVideos;

    /**
     * /3/tv/changes
     */
    public function changesTvList(?int $page = 1, ?string $startDate = null, ?string $endDate = null): ChangesTvList;

    /**
     * /3/tv/{series_id}/season/{season_number}/watch/providers - Get the list of streaming providers we have for a TV season.
     */
    public function tvSeasonWatchProviders(int $seasonNumber, int $seriesId, ?string $language = 'en-US'): TvSeasonWatchProviders;

    /**
     * /3/tv/episode/{episode_id}/changes - Get the recent changes for a TV episode.
     */
    public function tvEpisodeChangesById(int $episodeId): TvEpisodeChangesById;

    /**
     * /3/tv/episode_group/{tv_episode_group_id} - Get the details of a TV episode group.
     */
    public function tvEpisodeGroupDetails(string $tvEpisodeGroupId): TvEpisodeGroupDetails;

    /**
     * /3/tv/{series_id}/lists - Get the lists that a TV series has been added to.
     */
    public function listsCopy(int $seriesId, ?int $page = 1, ?string $language = 'en-US'): ListsCopy;
}